# Generated by Django 3.0.11 on 2021-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
