# Generated by Django 3.0.11 on 2021-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210426_2113'),
        ('report', '0003_auto_20210426_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ManyToManyField(null=True, to='project.Project'),
        ),
    ]
