# Generated by Django 3.1.7 on 2021-03-26 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='deputy_director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deputy_director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='info',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
