# Generated by Django 3.0.11 on 2021-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210326_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='logo',
            field=models.URLField(default='https://res.cloudinary.com/dj42j4pqu/image/upload/v1619305524/plfj8pvkj9pizrv9to57.png'),
        ),
    ]
