# Generated by Django 3.0.11 on 2021-03-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
