# Generated by Django 3.0.11 on 2021-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_user_imagetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageTest',
        ),
        migrations.AlterField(
            model_name='user',
            name='driving_license_img',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_img',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/dj42j4pqu/image/upload/v1619305524/plfj8pvkj9pizrv9to57.png'),
        ),
    ]
