# Generated by Django 3.0.11 on 2021-01-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auto_20210108_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/media/images/default.png', null=True, upload_to='images/'),
        ),
    ]
