# Generated by Django 3.0.11 on 2021-01-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_auto_20210108_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/images/default.png', null=True, upload_to='images/'),
        ),
    ]
