# Generated by Django 3.0.11 on 2021-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_auto_20210108_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=' images/default_8QB85hB.png ', null=True, upload_to='images/'),
        ),
    ]
