# Generated by Django 3.0.11 on 2021-02-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0011_auto_20210209_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
