# Generated by Django 3.1.4 on 2021-02-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='worker', max_length=50),
        ),
    ]
