# Generated by Django 3.1.4 on 2021-02-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0013_user_address'),
        ('worker', '0012_auto_20210212_1218'),
    ]

    operations = [
    ]
