# Generated by Django 3.1.4 on 2021-02-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0015_auto_20210212_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pay_pery_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
