# Generated by Django 3.1.4 on 2021-02-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0016_auto_20210212_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pay_pery_day',
            new_name='pay_per_day',
        ),
    ]
