# Generated by Django 3.0.11 on 2021-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0017_auto_20210212_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
