# Generated by Django 3.0.11 on 2021-07-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('month', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('month', models.DateField()),
                ('image', models.URLField(default='')),
                ('project', models.ManyToManyField(to='project.Project')),
            ],
        ),
    ]
