# Generated by Django 3.0.11 on 2021-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
