# Generated by Django 3.0.11 on 2021-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
