# Generated by Django 3.0.11 on 2021-05-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210426_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
