# Generated by Django 3.0.11 on 2021-06-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210426_2113'),
        ('finance', '0003_auto_20210508_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='project',
        ),
        migrations.AddField(
            model_name='income',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
