# Generated by Django 3.0.11 on 2021-03-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='data',
            new_name='date',
        ),
    ]
