# Generated by Django 3.0.11 on 2021-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20210328_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
