# Generated by Django 3.0.11 on 2021-06-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210426_2113'),
        ('mission', '0004_auto_20210605_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='project',
        ),
        migrations.AddField(
            model_name='mission',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
