# Generated by Django 3.0.11 on 2021-07-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=20, null=True)),
                ('building_image', models.URLField(default='')),
                ('project_code', models.CharField(blank=True, max_length=20, null=True)),
                ('contractor_first_name', models.CharField(blank=True, max_length=30)),
                ('contractor_second_name', models.CharField(blank=True, max_length=30)),
                ('contractor_phone_no', models.CharField(blank=True, max_length=25)),
                ('contractor_email', models.EmailField(blank=True, max_length=254)),
                ('architect_first_name', models.CharField(blank=True, max_length=30)),
                ('architect_second_name', models.CharField(blank=True, max_length=30)),
                ('architect_phone_no', models.CharField(blank=True, max_length=25)),
                ('architect_email', models.EmailField(blank=True, max_length=254)),
                ('address_link', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=20, null=True)),
                ('property_no', models.CharField(max_length=20, null=True)),
                ('owner_first_name', models.CharField(blank=True, max_length=30)),
                ('owner_second_name', models.CharField(blank=True, max_length=30)),
                ('owner_phone_no', models.CharField(blank=True, max_length=25)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('progress', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('project_code',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='project.Project')),
            ],
        ),
    ]
