# Generated by Django 3.0.11 on 2021-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20210101_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='building_image',
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
