# Generated by Django 3.0.11 on 2021-02-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20210221_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('project_code',)},
        ),
    ]
